Sf 1110
groupby/storefront-sort pull request #29
Opened 2018-09-25 15:22 UTC by zoomchik

2018-10-01 16:49 UTC, Vic-Dev requested changes
One change

2018-10-01 16:49 UTC, Vic-Dev commented on src/sort/index.ts
> +  getPastPurchasesLabel(sort: Store.Sort, index: number) {
this and `getLabel` use the same logic, so move that logic into a function which they both call

2018-10-01 16:51 UTC, Vic-Dev commented on src/sort/index.ts
> +    pastPurchasesLabels: string[];
Just noticing that the prop definition doesn't include `storeSection` please add it

2018-10-01 16:52 UTC, Vic-Dev requested changes
A couple additional things not directly related to this ticket, but important to add. Thank you!

2018-10-01 16:52 UTC, Vic-Dev commented on src/sort/index.ts
> +    pastPurchasesLabels: string[];
Just noticing that the prop definition doesn't include `storeSection` please add it

2018-10-01 16:52 UTC, Vic-Dev commented on src/sort/index.ts
> +    pastPurchasesLabels: []
should have a default for `storeSection` prop as `StoreSections.SEARCH`

2018-10-04 13:58 UTC, Vic-Dev commented on src/sort/index.ts
> +    pastPurchasesLabels: string[];
Actually it's defined on `Tag`. I added a commit to undo this work

2018-10-05 18:26 UTC, jmbtutor submitted a review, later dismissed
There's no differentiation between search and past purchase labels in `getLabel`. Please fix that and related tests. As well, please rebase on to the latest `master`.

2018-10-05 18:26 UTC, jmbtutor commented on src/sort/index.ts
>        return this.props.labels[index];
You need to differentiate between search sort labels and past purchase sort labels. This here always takes the search sort labels.

2018-10-05 18:26 UTC, jmbtutor commented on src/sort/index.ts
> +    pastPurchasesLabels: string[];
These props should be optional.

2018-10-08 07:51 UTC, zoomchik commented on src/sort/index.ts
>        return this.props.labels[index];
My fault, fixed

2018-10-09 17:15 UTC, Vic-Dev submitted a review, later dismissed

2018-10-09 17:18 UTC, Vic-Dev approved these changes

2018-10-09 17:19 UTC, merged